---
- hosts: all
  roles:
  - kwoodson.yedit

  tasks:
  - name: Install various required packages
    yum: name={{ item }} state=installed
    with_items:
      - wget
      - policycoreutils-python
      - epel-release
      - vim
      - python-passlib
      - httpd-tools
      - fail2ban

  - name: Enabling fail2ban
    copy:
      src: files/jail.local
      dest: /etc/fail2ban/jail.local

  - name: Enable fail2ban
    service:
      name: fail2ban
      state: started
      enabled: yes
  
  - name: Enforcing SELinux
    selinux:
      policy: targeted
      state: enforcing

  - name: Install docker
    yum: name={{ item }} state=installed
    with_items:
      - http://mirror.centos.org/centos/7/extras/x86_64/Packages/docker-1.13.1-63.git94f4240.el7.centos.x86_64.rpm

  - lineinfile:
      path: /etc/sysconfig/docker
      line: 'INSECURE_REGISTRY="--insecure-registry 172.30.0.0/16"'
  
  - name: Enable docker
    service: 
      name: docker
      state: started
      enabled: yes

  - name: Download openshift CLI
    get_url:
      url: https://github.com/openshift/origin/releases/download/v3.10.0/openshift-origin-client-tools-v3.10.0-dd10d17-linux-64bit.tar.gz
      dest: /tmp/origin.tgz

  - name: Extract openshift CLI
    unarchive:
      remote_src: True
      src: /tmp/origin.tgz
      dest: /tmp/

  - name: Copy files oc to /usr/local/bin
    copy:
      remote_src: True
      src: /tmp/openshift-origin-client-tools-v3.10.0-dd10d17-linux-64bit/oc
      dest: /usr/local/bin/

  - name: Changing perm of "/usr/local/bin/oc", adding "+x"
    file: 
      dest: /usr/local/bin/oc
      mode: a+x

  - name: Creates directory
    file: 
      path: /var/lib/openshift
      state: directory

  - name: Install OpenShift oc cluster up as Systemd Service
    template: 
      src: ../templates/openshift.service.j2
      dest: /etc/systemd/system/openshift.service
      owner: root
      group: root
      mode: 0755
    notify: Restart OpenShift


  - name: Enable and start OpenShift service
    service:
      name: openshift
      state: started
      enabled: yes

  - name: Create htpasswd
    htpasswd:
      path: /var/lib/openshift/openshift-apiserver/htpasswd
      name: admin
      password: 'admin'
      owner: root
      mode: 0640
  # oc cluster up with 3.10 does not support HTPassword
#  - name: Set HTPasswdIdentityProvider
#    yedit:
#      src: /var/lib/openshift/openshift-apiserver/master-config.yaml
#      key: oauthConfig.identityProviders[0]
#      backup: true
#      value:
#        challenge: true
#        login: true
#        mappingMethod: claim
#        name: anypassword
#        provider:
#          apiVersion: v1
#          kind: HTPasswdPasswordIdentityProvider
#          file: /var/lib/openshift/openshift-apiserver/htpasswd
#    notify: Restart OpenShift

  handlers:
  - name: Restart OpenShift
    service:
      name: openshift
      state: restarted




